### ISSUE TITLE
Esercizio 1.3

### ISSUE THREAD

**Issue by Pallalallo** [AnalistaProgrammatore/esercizi-javascript-12-02-Pallalallo#1]
Nell esercizio 1.3 viene invocata la funzione f ,senza definire il parametro y che prende in imput

**Comment by nonno-cicala** [comment]
Il codice è corretto e funziona sia su CodePen che su Node.js.
Alla riga 8 viene dichiarato che il parametro passato alla funzione _f_ avrà nome _y_ all'interno della funzione stessa. Quella funzione viene poi invocata in un altro punto del codice e le viene passato un parametro, l'esercizio richiede proprio di capire e descrivere cosa succeda.
Aiutati provando il codice e aggiungendo dei console.log che ti mostrino i contenuti delle variabili
