### ISSUE TITLE
Esercizio 1.4

### ISSUE THREAD

**Issue by Pallalallo** [AnalistaProgrammatore/esercizi-javascript-12-02-Pallalallo#2]
Alla fine assegna a z il valore di gg(), ma gg non è una funzione dichiarata, è una variabile a cui è stato attribuito un valore

**Comment by nonno-cicala** [comment]
Il codice è corretto e funziona sia su CodePen che su Node.js.
_gg_ è una funzione, puoi verificarlo eseguendo un _console.log(gg)_ dopo la dichiarazione di _gg_, cerca di capire perché
